description: My blog. Mostly about code, terrible decisions, running and podcasts.
url: http://coderick.com
permalink: /posts/:title
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
future: true
poole:
    word_separator: "-"
sass:
    sass_dir: _sass
    sourcemap: true
