# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: coderick
email: rick@coderick.com
description: > # this means to ignore newlines until "baseurl:"
  Hola! Soy Ricardo. No se como llegaste a este recondito rincon del internet,
  pero mientras estas aqui, deberias curiosear a ver si encuentras algun tema
  que te interese.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coderick.com" # the base hostname & protocol for your site
twitter_username: rasabatino
github_username:  coderickdotcom

# Build settings
markdown: kramdown
